package com.springmvc.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import com.springmvc.demo.adapter.UserAdapter;
import com.springmvc.demo.bo.Menu;
import com.springmvc.demo.bo.UserBO;
import com.springmvc.demo.dto.UserDTO;
import com.springmvc.demo.dto.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/database") // This means URL's start with /h2db (after Application path)
public class DatabaseController {
	private String ROOT_FOLDER = "h2db/";
	@Autowired // This means to get the bean called userRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	private String MENU_NAME = "Database";
	
	@Autowired
	private Menu menu;
	
	// Changes the current active button on the menu
	@ModelAttribute
	public void handleMenu() {
		menu.unactiveAll();
		menu.setActive(MENU_NAME);
	}
	

	// Index page
	@GetMapping("")
	public String index() {
		return ROOT_FOLDER + "h2dbindex";
	}

	@RequestMapping(value = "/getAllUsers")
	public ModelAndView getAllUsers() {
		ModelAndView modelAndView = new ModelAndView(ROOT_FOLDER + "h2dbAllUsers");
		modelAndView.addObject("allUsers", UserAdapter.usersDTOtoBO(userRepository.findAll()));
		return modelAndView;
	}

	@RequestMapping(value = "/getAllUsersAjax")
	public @ResponseBody Iterable<UserBO> getAllUsersAjax() {
		return UserAdapter.usersDTOtoBO(userRepository.findAll());
	}

}